version: '3.6'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.3.1
    ports:
     - 2181:2181
     - 2888:2888
     - 3888:3888
    environment:
     - ZOOKEEPER_CLIENT_PORT=2181
     - ZOOKEEPER_SERVER_ID=1
     - ZOOKEEPER_TICK_TIME=2000
     - ZOOKEEPER_SYNC_LIMIT=2
     - ZOOKEEPER_LOG4J_ROOT_LOGLEVEL=WARN
  kafka:
    image: confluentinc/cp-kafka:5.3.1
    ports:
     - 9092:9092
    links:
     - zookeeper
    environment:
     - KAFKA_BROKER_ID=1
     - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
     - KAFKA_KAFKA_HOST_NAME=kafka
     - KAFKA_LOG4J_ROOT_LOGLEVEL=WARN
     - KAFKA_TOOLS_LOG4J_LOGLEVEL=ERROR
     - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
     - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:19092,LISTENER_HOST://0.0.0.0:9092
     - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:19092,LISTENER_HOST://localhost:9092
     - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,LISTENER_HOST:PLAINTEXT
     - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
  schema-registry:
    image: confluentinc/cp-schema-registry:5.3.1
    ports:
     - 8081:8081
    environment:
     - SCHEMA_REGISTRY_HOST_NAME=schema-registry
     - SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS=PLAINTEXT://kafka:19092
     - SCHEMA_REGISTRY_LISTENERS=http://schema-registry:8081
     - SCHEMA_REGISTRY_DEBUG=false
    links:
     - zookeeper
     - kafka
  ksql:
    build: .
    image: ksql_issue_demo:5.3.1
    ports:
     - 8188:8188
    links:
     - kafka
     - schema-registry
    environment:
     - KSQL_BOOTSTRAP_SERVERS=kafka:19092
     - KSQL_KSQL_SERVICE_ID=ksql_headless_
     - KSQL_KSQL_SCHEMA_REGISTRY_URL=http://schema-registry:8081
     - KSQL_KSQL_QUERIES_FILE=/etc/kafka-ksql/ksql_issue_demo.ksql
     - KSQL_KSQL_SINK_WINDOW_CHANGE_LOG_ADDITIONAL_RETENTION=10000000000
     - KSQL_KSQL_STREAMS_AUTO_OFFSET_RESET=earliest
     - KSQL_KSQL_STREAMS_PRODUCER_ACKS=all
     - KSQL_KSQL_STREAMS_REPLICATION_FACTOR=1
     - KSQL_KSQL_SINK_REPLICAS=1
     - KSQL_KSQL_SINK_PARTITIONS=1
     - KSQL_LISTENERS=http://0.0.0.0:8188
     - KSQL_LOG4J_ROOT_LOGLEVEL=WARN
     - KSQL_TOOLS_LOG4J_ROOT_LOGLEVEL=WARN
  iksql:
    image: confluentinc/cp-ksql-server:5.3.1
    ports:
     - 8088:8088
    links:
     - kafka
     - schema-registry
    environment:
     - KSQL_HEAP_OPTS=-Xms768m -Xmx4096m
     - KSQL_BOOTSTRAP_SERVERS=kafka:19092
     - KSQL_KSQL_SCHEMA_REGISTRY_URL=http://schema-registry:8081
     - KSQL_KSQL_SERVICE_ID=interactive_
     - KSQL_KSQL_STREAMS_AUTO_OFFSET_RESET=earliest
     - KSQL_KSQL_STREAMS_PRODUCER_ACKS=all
     - KSQL_KSQL_STREAMS_REPLICATION_FACTOR=1
     - KSQL_KSQL_INTERNAL_TOPIC_REPLICAS=1
     - KSQL_KSQL_SINK_REPLICAS=1
     - KSQL_KSQL_SINK_PARTITIONS=1
     - KSQL_LISTENERS=http://0.0.0.0:8088
     - KSQL_LOG4J_ROOT_LOGLEVEL=WARN
     - KSQL_TOOLS_LOG4J_ROOT_LOGLEVEL=WARN
